#!/bin/sh
# Peixin You peixin.you
if [ -n "`echo $1|sed 's/[0-9]//g'`" ]
then
	echo 'Incorrect input'
	exit 2
else
    if [ $(($1 % 2)) -eq 0 ]
    then
        echo "even"
        exit 0
    else
        echo "odd"
        exit 1
    fi
fi