#!bin/sh
# Peixin You peixin.you
function listFiles()
{
    for file in `ls $2`;
    do
        if [ -d "$2/$file" ]; 
        then
            echo "$3 + $file"
            listFiles "$1" "$2/$file" "/$3"
        else
            if [ $1 == 1 ];
            then
                echo "$3 + $file"
            fi
        fi
    done
}
if [ $# == 0 ];
then
    listFiles 0 "." "/"
else
    listFiles 1 "." "/"
fi